### ISSUE TITLE
Choose an [open source] license

### ISSUE THREAD

**Issue by haesleinhuepf** [kwolbachia/Visualization_toolset#2]
Hi Kevin @kwolbachia ,

thanks for sharing this very practical toolset! I'm sure it will make many people's daily work easier. On the Image.sc forum you mentioned, people are welcome to "steal" code from it.
https://forum.image.sc/t/new-visualization-toolset/48592/6

I would recommend clarifying this here in your repository by adding an open source licence so that everyone knows under which conditions it is ok to reuse your intellectual property ;-)

There are websites which can help you making this decision which license such as https://choosealicense.com/ or consider unlicensing your code: https://unlicense.org/

Thanks again for your contribution to the ImageJ community 😃

Cheers,
Robert

**Comment by kwolbachia** [comment]
Hi Robert @haesleinhuepf ,

Thanks you for trying my tools! I really enjoy playing with ImageJ ^^
You're right I didn't realized the stealer side of this situation =P
I do it as soon as possible.

Cheers,
Kevin
